apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "api-core.fullname" . }}-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contato@gedui.com.br
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name:  {{ include "api-core.fullname" . }}-cert-issuer-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx