apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-core.fullname" . }}-ingress
  annotations:
    cert-manager.io/issuer: {{ include "api-core.fullname" . }}-cert-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  - hosts: |-
      {{- range .Values.apiCore.ingress.hosts }}
      - {{ . }}
      {{- end }}
    secretName: {{ include "api-core.fullname" . }}-cert-issuer
  rules:
  {{- range .Values.apiCore.ingress.hosts }}
  - http:
      paths:
      - pathType: Prefix
        path: {{ $.Values.apiCore.ingress.pathPrefix }}
        backend:
          service:
            name: {{ include "api-core.fullname" $ }}
            port:
              number: {{ $.Values.apiCore.service.port }}
    host: {{ . }}
  {{- end }}
