apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-core.fullname" . }}-ingress
  annotations:
    cert-manager.io/issuer: {{ include "api-core.fullname" . }}-cert-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.apiCore.ingress.host }}
    secretName: {{ include "api-core.fullname" . }}-cert-issuer
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ .Values.apiCore.ingress.pathPrefix }}
        backend:
          service:
            name: {{ include "api-core.fullname" . }}
            port:
              number: {{ .Values.apiCore.service.port }}
    {{- if .Values.apiCore.ingress.host }}
    host: {{ .Values.apiCore.ingress.host }}
    {{- end }}
