apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-core.fullname" . }}-ingress
  annotations:
    cert-manager.io/issuer: {{ include "api-core.fullname" . }}-cert-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  {{- range .Values.apiCore.ingress.hosts }}
  - hosts:
      - {{ .host }}
    secretName: {{ include "api-core.fullname" $ }}-cert-issuer
  {{- end }}
  rules:
  {{- range .Values.apiCore.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - pathType: {{ .pathType | default "Prefix" }}
        path: {{ .pathPrefix }}
        backend:
          service:
            name: {{ include "api-core.fullname" $ }}
            port:
              number: {{ $.Values.apiCore.service.port }}
      {{- end }}
  {{- end }}
